version: '3.8'

networks:
  inet:
    driver: bridge

services:
  db:
    container_name: postgres
    image: postgres:15
    restart: always
    expose:
      - 5432
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - inet

  fastapi:
    container_name: fastapi
    build: .
    command: bash -c 'alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload'
    volumes:
      - .:/vacancies
    ports:
      - "8000:8000"
    restart: always
    environment:
      DEBUG: 1
    networks:
      - inet
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis:7-alpine
    networks:
      - inet
    expose:
      - 6379

  celery:
    container_name: celery
    build: .
    command: celery -A src.celery_app.app.app worker --beat --loglevel=info
    volumes:
      - .:/vacancies
    depends_on:
      - redis
      - fastapi
    networks:
      - inet

  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    expose:
      - 9200
    networks:
      - inet

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./frontend/app:/frontend/app
      - ./frontend/public:/frontend/public
    networks:
      - inet

volumes:
  elasticsearch-data:
    driver: local
