version: '3.8'

networks:
  inet:
    driver: bridge

services:
  db:
    container_name: postgres
    image: postgres:15
    restart: always
    expose:
      - 5432
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - inet

  fastapi:
    container_name: fastapi
    build: .
    command: bash -c 'alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    networks:
      - inet
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis:7-alpine
    networks:
      - inet
    expose:
      - 6379

  celery:
    container_name: celery
    build: .
    command: celery -A src.celery_app.app.app worker --beat --loglevel=info
    volumes:
      - .:/vacancies
    depends_on:
      - redis
      - fastapi
    networks:
      - inet
